### PR TITLE
Revert changes that brokes build

### PR DESCRIPTION
**Pull request by ghost**
Hi!

My app became broken after some last changes and I prepared PR that fixes this for me.

I have no idea why its required to run npm install --only-dev on Heroku, modules in DEV are will NOT be installed in non-dev mode as Heroku used by almost all people :)

### CODE REVIEW

**Comment by febeling** [comment]
Thanks for the PR and sorry for the trouble. Could you provide a gist with you packages.json? 

For your question: The `dependencies` packages are installed by the node buildpack, not by webpack-rails-buildpack. webpack-rails-buildpack only installs `devDependencies` for running webpack once.

I'd like to better understand before revoking the change.

**Comment by ghost** [comment]
Hello)

This is gist for our packages.json (I just removed from there some titles - private info): 

https://gist.github.com/vladimirbazhanov/326e232f4fcc7de5555cad9c57249695

I see what is idea - to have prod deps installed by node webpack and after that have dev deps installed by webpack, but seems like something was wrong with this.

I'm not a professional with node/webpack so I can't suggest fix or say "I'm sure that is broken", just want to notify you about problems ))

**Comment by febeling** [comment]
You have a number of `devDependencies` declared as regular `dependencies`. That doesn't really explain how it fails in your case, though. It should still work, as dependencies should still be there. 

Do you have log output by any chance?

**Comment by febeling** [comment]
Whoever else is experiencing a similar problem can use the `leave_dev_deps` branch in the meantime. Reference it by:
```
https://github.com/febeling/webpack-rails-buildpack.git#leave_dev_deps
```

**Comment by cgc** [comment]
@vladimirbazhanov I forked your gist to [here](https://gist.github.com/cgc/3051354fe922967b82126386db5dff70) and was able to deploy it fine with the following buildpacks:
```bash
1. heroku/ruby
2. heroku/nodejs
3. https://github.com/febeling/webpack-rails-buildpack.git
```

can you share the log from your failed build (in a gist)?

**Comment by febeling** [comment]
I assume that the change is working for correct dependency definitions, otherwise we'd have heard more about this. I'm closing. Please reopen if you think this is mistaken.

**Pull request closed without merging**
